name: 'Get Conan'
description: 'Installs Conan'
author: 'TurtleBrowser'
inputs:
  version:
    description: "Wanted conan version"
    required: false
    default: ''
outputs:
  version:
    description: "The version of Conan which was installed"
    value: ${{ steps.output_version.outputs.version }}
runs:
  using: "composite"
  steps:
    - name: Install setup tools
      if: ${{ !env.IS_MAC }}
      run: pip3 install wheel setuptools
      shell: bash
    - name: Install conan latest (pip)
      if: ${{ inputs.version == '' && runner.os != 'macOS'  }}
      run: pip3 install conan --upgrade
      shell: bash
    - name: Install conan version ${{ inputs.version }} (pip)
      if: ${{ inputs.version != '' && runner.os != 'macOS' }}
      run: pip3 install conan==${{ inputs.version }} --upgrade
      shell: bash
    - name: Install conan latest (brew)
      if: ${{ inputs.version == '' && runner.os == 'macOS'  }}
      run: brew install conan
      shell: bash
    - name: Install conan version ${{ inputs.version }} (brew)
      if: ${{ inputs.version != '' && runner.os == 'macOS' }}
      run: brew install conan@${{ inputs.version }}
      shell: bash
    - name: Fix path on Linux
      run: |
        echo "/home/runner/.local/bin" >> $GITHUB_PATH
      shell: bash
    - name: Fill in output variable
      id: output_version
      shell: bash
      run: |
        conan --version
        echo "version=$(conan --version)" >> $GITHUB_OUTPUT
branding:
  icon: "archive"
  color: "green"
